import type { Metadata } from "next";
import "./globals.css";

import AppSidebar from "@/components/common/Sidebar/AppSidebar";
import TopNavbar from "@/components/common/TopNavbar/TopNavbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Poppins } from "next/font/google";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased min-h-screen flex`}>
        {modal}
        <SidebarProvider>
          <AppSidebar />
          <main className="flex flex-col flex-1">
            <TopNavbar />
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
